FROM docker.io/library/golang:1.23-alpine AS build

WORKDIR /app
COPY go.mod ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -trimpath -ldflags="-s -w" -o /out/server ./cmd/server

FROM scratch

COPY --from=build /out/server /server

EXPOSE 8080
ENTRYPOINT ["/server"]
